name: Export Notion to Telegram
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 19 * *'
jobs:
  export_notion:
    # timeout-minutes: 360
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm dependencies cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Playwright cache
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - name: Run Notion Export
        run: node notion-export.js
        env:
          NOTION_USERNAME: ${{secrets.NOTION_USERNAME}}
          NOTION_PASSWORD: ${{secrets.NOTION_PASSWORD}}
          NOTION_ARCHIVE_URL: ${{secrets.NOTION_ARCHIVE_URL}}
          NOTION_TOKEN_V2: ${{secrets.NOTION_TOKEN_V2}}
          NOTION_FILE_TOKEN: ${{secrets.NOTION_FILE_TOKEN}}
          NOT_HEADLESS: 0
          
      - name: Upload Notion Export Data Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: notion-export
          path: data/

      - name: Upload Screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: screenshots
          path: screenshot/

  # upload_telegram:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - uses: actions/checkout@v3
  #       - uses: actions/setup-node@v3
  #         with:
  #           node-version: 18
  #       - name: Install dependencies
  #         run: npm ci
  #       - name: Install Playwright Browsers
  #         run: npx playwright install --with-deps
  #       - name: Run Telegram Upload
  #         run: node telegram-upload.js
